services:
  - type: web
    name: kfm-delice
    env: node
    region: oregon
    plan: free
    branch: master
    autoDeploy: true
    buildCommand: npm run build
    startCommand: chmod +x ./scripts/start-render.sh && ./scripts/start-render.sh
    numInstances: 1
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_DIRECT
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://kfm-delice.onrender.com
      - key: NEXT_PUBLIC_APP_NAME
        value: KFM DELICE
    healthCheckPath: /api/health
