services:
  - type: web
    name: kfm-delice
    env: node
    region: oregon
    plan: free
    buildCommand: npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        value: https://kfm-delice.onrender.com
      - key: NEXT_PUBLIC_APP_NAME
        value: KFM DELICE
    healthCheckPath: /
