/// <reference lib="webworker" />

declare const self: ServiceWorkerGlobalScope;

import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { Queue } from 'workbox-background-sync';

// ============================================
// Restaurant OS - Service Worker
// Offline-first PWA support
// ============================================

// Claim clients immediately
self.skipWaiting();
clientsClaim();

// ============================================
// Precaching
// ============================================

// Precache all static assets generated by Next.js
precacheAndRoute(self.__WB_MANIFEST);

// Use a stale-while-revalidate strategy for all other requests
const handler = createHandlerBoundToURL('/index.html');
registerRoute(
  ({ request, url }) => {
    // If this isn't a navigation request, skip
    if (request.mode !== 'navigate') {
      return false;
    }
    // If this is a URL for static files, skip
    if (url.pathname.startsWith('/_next')) {
      return false;
    }
    // Return true for navigation requests
    return true;
  },
  handler
);

// ============================================
// Offline Background Sync Queue
// ============================================

// Queue for offline order submissions
const orderQueue = new Queue('order-queue', {
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request);
        console.log('Background sync: Order submitted successfully');
        
        // Notify the client
        const clients = await self.clients.matchAll();
        clients.forEach(client => {
          client.postMessage({
            type: 'ORDER_SYNCED',
            payload: { url: entry.request.url }
          });
        });
      } catch (error) {
        console.error('Background sync: Failed to submit order', error);
        // Put the request back in the queue if it failed
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  }
});

// Queue for offline payment submissions
const paymentQueue = new Queue('payment-queue', {
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        await fetch(entry.request);
        console.log('Background sync: Payment submitted successfully');
        
        const clients = await self.clients.matchAll();
        clients.forEach(client => {
          client.postMessage({
            type: 'PAYMENT_SYNCED',
            payload: { url: entry.request.url }
          });
        });
      } catch (error) {
        console.error('Background sync: Failed to submit payment', error);
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  }
});

// ============================================
// Caching Strategies
// ============================================

// Cache static assets (JS, CSS, images)
registerRoute(
  ({ request }) =>
    request.destination === 'style' ||
    request.destination === 'script' ||
    request.destination === 'worker' ||
    request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'static-assets',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Cache fonts
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache API responses (network first, fallback to cache)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
    networkTimeoutSeconds: 10,
  }),
  'GET'
);

// Handle POST requests for offline orders
registerRoute(
  ({ url, request }) => 
    url.pathname === '/api/orders' && request.method === 'POST',
  async ({ request }) => {
    try {
      // Try to send the request
      const response = await fetch(request.clone());
      return response;
    } catch (error) {
      // If offline, add to queue
      await orderQueue.pushRequest({ request: request.clone() });
      
      // Return a custom response
      return new Response(
        JSON.stringify({
          success: true,
          message: 'Commande enregistrée hors ligne. Elle sera synchronisée automatiquement.',
          offline: true,
        }),
        {
          headers: { 'Content-Type': 'application/json' },
        }
      );
    }
  },
  'POST'
);

// Handle POST requests for offline payments
registerRoute(
  ({ url, request }) => 
    url.pathname === '/api/payments' && request.method === 'POST',
  async ({ request }) => {
    try {
      const response = await fetch(request.clone());
      return response;
    } catch (error) {
      await paymentQueue.pushRequest({ request: request.clone() });
      
      return new Response(
        JSON.stringify({
          success: true,
          message: 'Paiement enregistré hors ligne. Il sera synchronisé automatiquement.',
          offline: true,
        }),
        {
          headers: { 'Content-Type': 'application/json' },
        }
      );
    }
  },
  'POST'
);

// ============================================
// Push Notifications
// ============================================

interface PushNotificationData {
  title: string;
  body: string;
  icon?: string;
  badge?: string;
  tag?: string;
  data?: {
    url?: string;
    type?: string;
    id?: string;
  };
  actions?: Array<{
    action: string;
    title: string;
    icon?: string;
  }>;
}

self.addEventListener('push', (event: PushEvent) => {
  const data: PushNotificationData = event.data?.json() ?? {
    title: 'Restaurant OS',
    body: 'Nouvelle notification',
  };

  const options: NotificationOptions = {
    body: data.body,
    icon: data.icon || '/icons/icon-192x192.png',
    badge: data.badge || '/icons/badge-72x72.png',
    tag: data.tag || 'default',
    data: data.data,
    actions: data.actions,
    vibrate: [100, 50, 100],
    requireInteraction: true,
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Handle notification click
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      // Check if there's already a window open
      for (const client of clients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          if ('navigate' in client) {
            (client as WindowClient).navigate(urlToOpen);
          }
          return;
        }
      }
      // Open a new window if no existing window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Handle notification action clicks
self.addEventListener('notificationclick', (event: NotificationEvent) => {
  const action = event.action;
  
  if (action === 'accept') {
    // Handle accept action
    event.waitUntil(
      fetch('/api/notifications/respond', {
        method: 'POST',
        body: JSON.stringify({
          notificationId: event.notification.data?.id,
          action: 'accepted',
        }),
        headers: { 'Content-Type': 'application/json' },
      })
    );
  } else if (action === 'reject') {
    // Handle reject action
    event.waitUntil(
      fetch('/api/notifications/respond', {
        method: 'POST',
        body: JSON.stringify({
          notificationId: event.notification.data?.id,
          action: 'rejected',
        }),
        headers: { 'Content-Type': 'application/json' },
      })
    );
  }
});

// ============================================
// Periodic Background Sync
// ============================================

self.addEventListener('periodicsync', (event: PeriodicSyncEvent) => {
  if (event.tag === 'sync-orders') {
    event.waitUntil(syncOrders());
  } else if (event.tag === 'sync-deliveries') {
    event.waitUntil(syncDeliveries());
  }
});

async function syncOrders(): Promise<void> {
  try {
    const response = await fetch('/api/orders/sync');
    const data = await response.json();
    
    const clients = await self.clients.matchAll();
    clients.forEach(client => {
      client.postMessage({
        type: 'ORDERS_SYNCED',
        payload: data,
      });
    });
  } catch (error) {
    console.error('Periodic sync: Failed to sync orders', error);
  }
}

async function syncDeliveries(): Promise<void> {
  try {
    const response = await fetch('/api/deliveries/sync');
    const data = await response.json();
    
    const clients = await self.clients.matchAll();
    clients.forEach(client => {
      client.postMessage({
        type: 'DELIVERIES_SYNCED',
        payload: data,
      });
    });
  } catch (error) {
    console.error('Periodic sync: Failed to sync deliveries', error);
  }
}

// ============================================
// Message Handling
// ============================================

self.addEventListener('message', (event: ExtendableMessageEvent) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  
  if (event.data && event.data.type === 'GET_VERSION') {
    event.ports[0].postMessage({ version: '1.0.0' });
  }
  
  if (event.data && event.data.type === 'CLEAR_CACHE') {
    event.waitUntil(
      caches.keys().then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => caches.delete(cacheName))
        );
      }).then(() => {
        event.ports[0].postMessage({ success: true });
      })
    );
  }
});

export {};
